In [35]:
# Import Pandas
import pandas as pd

#Load Data
data = pd.read_csv('/content/judge-1377884607_tweet_product_company.csv',encoding='ISO-8859-1')
data.head(3)

,tweet_text,emotion_in_tweet_is_directed_at,is_there_an_emotion_directed_at_a_brand_or_product
0,.@wesley83 I have a 3G iPhone. After 3 hrs twe...,iPhone,Negative emotion
1,@jessedee Know about @fludapp ? Awesome iPad/i...,iPad or iPhone App,Positive emotion
2,@swonderlin Can not wait for #iPad 2 also. The...,iPad,Positive emotion

In [36]:
data.info() # Data info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9093 entries, 0 to 9092
Data columns (total 3 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   tweet_text                                          9092 non-null   object
 1   emotion_in_tweet_is_directed_at                     3291 non-null   object
 2   is_there_an_emotion_directed_at_a_brand_or_product  9093 non-null   object
dtypes: object(3)
memory usage: 213.2+ KB

In [37]:
df=data.drop("emotion_in_tweet_is_directed_at",axis=1) #drop the id column

In [38]:
import pandas as pd
import re # for replacing
import nltk # natural language tool kit
from nltk.corpus import stopwords # Importing stopwords

nltk.download('stopwords') # downloading stop words
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = str(text).lower() # converting to Lowercase
    text = re.sub(r'http\S+|@\w+|#\w+', '', text) # Removing http,@,# char and replace it with ''
    text = re.sub(r'[^a-z\s]', '', text) # only keep letters and replace all others with ''
    words = text.split() # splitting the words
    words = [w for w in words if w not in stop_words] # will not include stopwords
    return " ".join(words)

df['clean_text'] = df['tweet_text'].apply(clean_text)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [39]:
df["is_there_an_emotion_directed_at_a_brand_or_product"].value_counts() # Getting Valuecounts

is_there_an_emotion_directed_at_a_brand_or_product
No emotion toward brand or product    5389
Positive emotion                      2978
Negative emotion                       570
I can't tell                           156
Name: count, dtype: int64

In [40]:
df

,tweet_text,is_there_an_emotion_directed_at_a_brand_or_product,clean_text
0,.@wesley83 I have a 3G iPhone. After 3 hrs twe...,Negative emotion,g iphone hrs tweeting dead need upgrade plugin...
1,@jessedee Know about @fludapp ? Awesome iPad/i...,Positive emotion,know awesome ipadiphone app youll likely appre...
2,@swonderlin Can not wait for #iPad 2 also. The...,Positive emotion,wait also sale
3,@sxsw I hope this year's festival isn't as cra...,Negative emotion,hope years festival isnt crashy years iphone app
4,@sxtxstate great stuff on Fri #SXSW: Marissa M...,Positive emotion,great stuff fri marissa mayer google tim oreil...
...,...,...,...
9088,Ipad everywhere. #SXSW {link},Positive emotion,ipad everywhere link
9089,"Wave, buzz... RT @mention We interrupt your re...",No emotion toward brand or product,wave buzz rt interrupt regularly scheduled gee...
9090,"Google's Zeiger, a physician never reported po...",No emotion toward brand or product,googles zeiger physician never reported potent...
9091,Some Verizon iPhone customers complained their...,No emotion toward brand or product,verizon iphone customers complained time fell ...
9092,Ï¡Ïàü_ÊÎÒ£Áââ_£â_ÛâRT @...,No emotion toward brand or product,rt google tests checkin offers link

In [54]:
# Import Numpy,Pandas
import numpy as np
import pandas as pd

In [42]:
# Tokenization + Padding
from tensorflow.keras.preprocessing.text import Tokenizer #imported Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences #imported pad_Sequence

tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(df['clean_text'])

seqs = tokenizer.sequences_to_texts(df['clean_text']) # Text to seq
X_pad = pad_sequences(seqs, maxlen=100) # maxlength for each tweet

In [43]:
# 1.RNN
from tensorflow.keras.models import Sequential # Importing Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense # Importing RNN,Simple Rnn,Dense

model = Sequential([
    Embedding(5000, 128),
    SimpleRNN(64),
    Dense(13, activation='softmax')
])

In [44]:
from tensorflow.keras.preprocessing.text import Tokenizer# Importing Tokenizer and Pad_sequence
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(num_words=5000) # keeps only top 5000 frequent words
tokenizer.fit_on_texts(df['clean_text'])

X = tokenizer.texts_to_sequences(df['clean_text'])# Text to Sequence
X = pad_sequences(X, maxlen=100)

In [45]:
from sklearn.preprocessing import LabelEncoder# Importing Label encoder

le = LabelEncoder()
y = le.fit_transform(df['is_there_an_emotion_directed_at_a_brand_or_product']) # Encoding the y

print(y[:5])

[1 3 3 1 3]

In [46]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=5)

Epoch 1/5
285/285 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.5929 - loss: 0.9984
Epoch 2/5
285/285 ━━━━━━━━━━━━━━━━━━━━ 8s 29ms/step - accuracy: 0.6864 - loss: 0.7531
Epoch 3/5
285/285 ━━━━━━━━━━━━━━━━━━━━ 11s 32ms/step - accuracy: 0.8003 - loss: 0.5209
Epoch 4/5
285/285 ━━━━━━━━━━━━━━━━━━━━ 10s 34ms/step - accuracy: 0.8577 - loss: 0.3709
Epoch 5/5
285/285 ━━━━━━━━━━━━━━━━━━━━ 10s 34ms/step - accuracy: 0.8841 - loss: 0.2885

In [47]:
new_text = ["I am very happy today"]

# step 1: tokenize
seq = tokenizer.texts_to_sequences(new_text)

# step 2: pad
padded = pad_sequences(seq, maxlen=100)

# step 3: predict
pred = model.predict(padded)

print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step
[[1.8639837e-03 2.3729578e-03 3.2854176e-01 6.6548586e-01 2.4892623e-04
  7.4391835e-05 2.1628611e-04 1.8048492e-04 5.9710448e-05 1.3483858e-04
  3.0996036e-04 2.2809709e-04 2.8287878e-04]]

In [48]:
import numpy as np

pred_class = np.argmax(pred)
print(pred_class)

3

In [49]:
label = le.inverse_transform([pred_class])
print(label[0])

Positive emotion

In [50]:
#2.lstm

from tensorflow.keras.layers import LSTM

model = Sequential([
    Embedding(5000, 128),
    LSTM(64),
    Dense(13, activation='softmax')
])

In [51]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,      # 20% test data
    random_state=42     # reproducibility
)

In [52]:
model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5
228/228 ━━━━━━━━━━━━━━━━━━━━ 18s 70ms/step - accuracy: 0.5909 - loss: 0.9895 - val_accuracy: 0.6146 - val_loss: 0.8623
Epoch 2/5
228/228 ━━━━━━━━━━━━━━━━━━━━ 16s 68ms/step - accuracy: 0.6845 - loss: 0.7654 - val_accuracy: 0.6614 - val_loss: 0.8306
Epoch 3/5
228/228 ━━━━━━━━━━━━━━━━━━━━ 17s 73ms/step - accuracy: 0.7732 - loss: 0.6049 - val_accuracy: 0.6690 - val_loss: 0.8553
Epoch 4/5
228/228 ━━━━━━━━━━━━━━━━━━━━ 15s 68ms/step - accuracy: 0.8178 - loss: 0.4914 - val_accuracy: 0.6652 - val_loss: 0.8982
Epoch 5/5
228/228 ━━━━━━━━━━━━━━━━━━━━ 22s 75ms/step - accuracy: 0.8444 - loss: 0.4162 - val_accuracy: 0.6718 - val_loss: 0.9959

In [53]:
new_text = ["I don't Like this product.I get's hang every time"]

seq = tokenizer.texts_to_sequences(new_text)
padded = pad_sequences(seq, maxlen=100)

pred = model.predict(padded)

import numpy as np
pred_class = np.argmax(pred)

print("Predicted Class:", pred_class)
label = le.inverse_transform([pred_class])
print(label[0])

WARNING:tensorflow:5 out of the last 10 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7b272d02cc20> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 532ms/step
Predicted Class: 1
Negative emotion